# Generated by Django 4.2 on 2023-04-11 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, null=True)),
                ('image', models.CharField(max_length=15, null=True)),
                ('author', models.CharField(max_length=15, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('title', models.CharField(max_length=30, null=True)),
                ('shortContent', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
