# Generated by Django 4.2 on 2023-04-11 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=15)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('title', models.CharField(max_length=30)),
                ('shortContent', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
