# Generated by Django 4.2 on 2023-04-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
