# Generated by Django 4.2 on 2023-04-11 01:28

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_addpost_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='author',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='content',
            field=blog.models.NonStrippingTextField(),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='image',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='shortContent',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='slug',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addpost',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
